title: Ben Hodson
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6176487721968442
  brandStrength: 0.1587804090231657
  rhythmicContrast: 0.3314003981649876
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  lightness: 0.680791565682739
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: Tracking ID UA-75664456-1
  facebook: null
name: benhodson
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3604082413949072
layout_spectrum: 1
