name: benhodson
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5168
title: Ben Hodson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: Tracking ID UA-75664456-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c8bfbd'
    - '#1d4552'
    - '#426972'
    - '#738a93'
    - '#a8a9ae'
  brandStrength: 0.75
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
