name: benhodson
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5168
title: Ben Hodson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: Tracking ID UA-75664456-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c8d0da'
    - '#8593a6'
    - '#323033'
    - '#713900'
  brandStrength: 0.1875
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
