name: benhodson
favicon: null
layout_spectrum: 0.7078907340764999
typography_spectrum: 0.5168
title: Ben Hodson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: Tracking ID UA-75664456-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3e3e3'
    - '#181818'
    - '#43a5df'
    - '#868686'
    - '#187bbb'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.6176487721968442
  rhythmicContrast: 0.75
purpose: []
